### ISSUE TITLE
mdeforg dosen't run from source code

### ISSUE THREAD

**Issue by masomheidari** [MDEGroup/MDEForge#74]
I am unable to run mdeforg from source code,I received the following error 

RROR [localhost-startStop-1] org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.validation.beanvalidation.LocalValidatorFactoryBean#0': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/validation/ParameterNameProvider
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)

**Comment by md2manoppello** [comment]
Do you run in stand alone mode or in tomcat7 application server? I'm traveling, When I come back to home I support you to run it.

**Comment by masomheidari** [comment]
In Tomcat7 which I config it on Eclipse.Is it related to version of Tomact?thanks for your support.
